# Generated by Django 5.1.1 on 2024-09-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_bus_number_bus_category_bus_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
    ]
