# Generated by Django 5.1.1 on 2024-09-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_location_location_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='locations',
            new_name='location',
        ),
    ]
