# Generated by Django 5.1.1 on 2024-09-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_locations_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_updated',
        ),
    ]
