# Generated by Django 5.1.1 on 2024-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_schedule_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
