# Generated by Django 5.1.1 on 2024-09-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='date_updated',
        ),
    ]
